class ZigAttestationData:
    def payload_bytes(self) -> bytes: ...
    def payload_kind(self) -> str: ...

def zig_attestation_data_from_ssz_bytes(*, payload: bytes) -> ZigAttestationData: ...

def zig_attestation_data_from_response_json_bytes(*, payload: bytes) -> ZigAttestationData: ...
