class ZigAttestationData:
    def hash_tree_root_hex(self) -> str: ...

def zig_attestation_data_from_ssz_bytes(payload: bytes) -> ZigAttestationData: ...

def zig_attestation_data_from_response_json_bytes(payload: bytes) -> ZigAttestationData: ...

def zig_beacon_block_body_root_from_ssz_bytes(payload: bytes) -> str: ...
